version: "3.8"

volumes:
 prometheus_data: {}
 grafana_data: {}
 etc_motioneye:
 var_lib_motioneye:

services:
 server:
  build: "./server"
  privileged: true
  restart: always
  ports:
  - 3000:3000
  volumes:
  - /dev:/dev
 prometheus:
  image : prom/prometheus
  container_name: prometheus
  volumes:
   - ./prometheus/:/etc/prometheus/
   - prometheus_data:/prometheus
  ports:
  - 9090:9090
  restart: always
 grafana:
  image : grafana/grafana
  user: "472"
  container_name: grafana
  depends_on:
   - prometheus
  volumes:
   - grafana_data:/var/lib/grafana
   - ./grafana/provisioning/:/etc/grafana/provisioning/
   - ./grafana/config/custom.ini:/etc/grafana/grafana.ini
  ports:
  - 4200:3000
  restart: always
  # motioneye:
  # image: ccrisan/motioneye:master-armhf # Change to ccrisan/motioneye:master-armhf for ARM chips (Pi etc.)
  # devices:
  # - "/dev/video0:/dev/video0"
  # ports:
  # - 8081:8081
  # - 8765:8765
  # volumes:
  #  - /home/ubuntu/motioneye:/var/lib/motioneye
