version: "3.8"

volumes:
 prometheus_data: {}
 grafana_data: {}

services:
 mhz19:
  build: "./mh-z19"
  ports:
  - 3000:3000
  volumes:
  - .:/code
 prometheus:
  image : prom/prometheus
  container_name: prometheus
  volumes:
   - ./prometheus/:/etc/prometheus/
   - prometheus_data:/prometheus
  ports:
  - 9090:9090
  restart: always
 grafana:
  image : grafana/grafana
  user: "472"
  container_name: grafana
  depends_on:
   - prometheus
  volumes:
   - grafana_data:/var/lib/grafana
   - ./grafana/provisioning/:/etc/grafana/provisioning/
  ports:
  - 4200:3000
  restart: always
